src/libaudgui/prefs-window.cc
src/libaudqt/prefs-window.cc

Hi, I've added support for SOCKS proxy.  Please review/comment and merge if you agree with it. There is also a second part in audacious-plugins.
I've tested it with GTK+ 2/3 (Linux) and Qt (Linux and Windows).
Note that in libaudgui/prefs-window.cc I did not put radio buttons to proxy_socks_elements[] because they were not showing up.  For libaudqt/prefs-window.cc it works that way.

Add SOCKS proxy support.

---

src/audacious/Makefile
src/libaudgui/Makefile
src/libaudqt/Makefile
src/libaudtag/Makefile

`${LDFLAGS}` often contains additional (system) library directories that
also often contain old/already installed versions of the libraries to be
linked and are passed via `${LIBS}`. While `${LIBS}` pretty much always
contains `-Llocal_build_dir` to make the linker/compiler pick the newly
built library for the later referenced libraries, that location will be
overridden and the build system hence eventually tries to link against
the old system library.
This issue is not seen often on Linux-based systems (since they don't
need to supply additional system library directories), but abundant on
others.
For instance, on macOS with MacPorts, `LDFLAGS` contains `-L${prefix}/lib`
(with `/opt/local` being the default prefix).
This leads to link calls such as these:
```
$LD ... -L${prefix}/lib ... …
```

misc Makefile: move build artifacts dirs into *LDFLAGS variable.

---

src/libaudcore/tuple.cc

I'm writing a plugin where the possibly only tuple info that may get updated upon playback is the duration. Noticed nothing was happening, when set_playback_tuple was called, although read_tags works, since that path apparently doesn't depend on this test.

Fix accidental assignment instead of compare in Tuple::is_same.

---

src/libaudqt/song-window-qt.cc

- Replace the unnecessary QComboBox with a QLineEdit
- Toggle the text of the 'Queue' button based on whether the currently selected entry is already queued or not.

audqt: Improve the 'Jump to Song' dialog further

---

audacious.desktop

Since this commit (https://github.com/KDE/plasma-workspace/commit/ebd2acd98ecdb9d115b01bd01f532390376152f7),
Plasma Desktop will check "X-GNOME-SingleWindow" property to determine
whether to show "Open New Window" action in the context menu of a task.
Audacious cannot launch a new instance or open a new window, so add the
property and set it to true to hide the action.
|Before|After|
|--|--|
|![before](https://user-images.githubusercontent.com/23738961/147640798-d66ad00a-c0af-4af1-9cf8-c39549beb80e.png)|![after](https://user-images.githubusercontent.com/23738961/147640820-6fec3537-e4a7-472b-8956-ee5a90512727.png)|

Add "X-GNOME-SingleWindow=true" to the desktop file

---

audacious.desktop

X-GNOME-SingleWindow was upstreamed to be an XDG spec with the name "SingleMainWindow" in https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/53

Change X-GNOME-SingleWindow key to SingleMainWindow

---

src/libaudgui/infowin.cc

This commit updates the unit formatting for bitrates to the universal
symbol from the now deprecated abbreviation.

Fix bitrate unit formatting

---

configure.ac
src/libaudcore/Makefile
src/libaudcore/playlist-utils.cc
src/libaudcore/playlist.h
src/libaudcore/tuple.cc
src/libaudcore/tuple.h
src/libaudqt/info-widget.cc
src/libaudtag/id3/id3-common.cc
src/libaudtag/id3/id3v24.cc

I wanted to see the publisher (label) and catalog number tags in a playlist, but noticed that it wasn't implemented. This adds `Publisher` and `CatalogNum` to `Tuple` as well as support for ID3v2.4 tags.
Corresponding plugins PR to add support to qtui, gtkui, flac, and vorbis: audacious-media-player/audacious-plugins#111

Add publisher and catalog number

---

acinclude.m4
meson.build
meson_options.txt
src/config.h.meson
src/libaudgui/Makefile
src/libaudgui/about.cc
src/libaudgui/eq-preset.cc
src/libaudgui/equalizer.cc
src/libaudgui/file-opener.cc
src/libaudgui/gtk-compat.cc
src/libaudgui/gtk-compat.h
src/libaudgui/infopopup.cc
src/libaudgui/infowin.cc
src/libaudgui/jump-to-track.cc
src/libaudgui/list.cc
src/libaudgui/menu.cc
src/libaudgui/meson.build
src/libaudgui/plugin-prefs.cc
src/libaudgui/plugin-view.cc
src/libaudgui/prefs-widget.cc
src/libaudgui/prefs-window.cc
src/libaudgui/scaled-image.cc
src/libaudgui/status.cc
src/libaudgui/url-opener.cc
src/libaudgui/util.cc

- Add a slim compatibility layer (gtk-compat.h) which makes it pretty straightforward
to support both GTK versions in one code base.
- GTK2 is still the default (requested by @jlindgren90).
GTK3 can be enabled with "--enable-gtk3", or when using Meson with "-D gtk3=true".
- Require at least GTK 3.22 (released in 2016) to avoid specific GTK version checks
and make use of recent APIs if possible.
- Since GTK2 is end of life upstream, modern distributions may have stopped to ship
Audacious with GTK support. Now they can do that again with GTK3 and Qt combined
or as separate packages.

audgui: Restore GTK3 support

---

.github/actions/install-dependencies/action.yml
.github/actions/install-dependencies/install-dependencies.sh
.github/actions/run-action/action.yml
.github/actions/run-action/run-action.sh
.github/workflows/c-cpp.yml

This allows us to build these configurations simultaneously and each one with Autotools and Meson:
- Ubuntu 20.04 with GTK2 and Qt 5
- Ubuntu 22.04 with GTK3 and Qt 5
- macOS 12     with Qt 5 or  Qt 6

CI: Implement build matrix for multiple OS's and build systems

---

meson.build

meson has issues finding libintl in FreeBSD, work around it.
Ref.: https://github.com/mesonbuild/meson/issues/4468
https://github.com/mesonbuild/meson/pull/8875

meson: Fix missing libintl

---

src/libaudgui/about.cc
src/libaudgui/eq-preset.cc
src/libaudgui/equalizer.cc
src/libaudgui/file-opener.cc
src/libaudgui/infopopup.cc
src/libaudgui/infowin.cc
src/libaudgui/jump-to-track.cc
src/libaudgui/plugin-prefs.cc
src/libaudgui/prefs-window.cc
src/libaudgui/queue-manager.cc
src/libaudgui/status.cc
src/libaudgui/util.cc
src/libaudqt/about-qt.cc
src/libaudqt/audqt.cc
src/libaudqt/colorbutton.cc
src/libaudqt/eq-preset-qt.cc
src/libaudqt/file-entry.cc
src/libaudqt/fileopener.cc
src/libaudqt/infowin-qt.cc
src/libaudqt/log-inspector.cc
src/libaudqt/playlist-management.cc
src/libaudqt/prefs-plugin.cc
src/libaudqt/prefs-window-qt.cc
src/libaudqt/queue-manager-qt.cc
src/libaudqt/song-window-qt.cc
src/libaudqt/url-opener-qt.cc

With window managers like icewm and i3 users can configure window specific settings. For this to work toplevel windows must be distinguishable by a X11 property. Because Audacious uses the same WM_CLASS property for all its windows, the WM_WINDOW_ROLE property must be set. However, Audacious currently does not set this property. It is defined in the ICCCM manual for X11 clients. This patch sets this property on Gtk and Qt toplevel windows using designated library calls.

Add a WM_WINDOW_ROLE property to toplevel X11 windows.

---

meson.build

CYGWIN uses shared libraries with `.dll` extension like Windows.
This patch fixes `meson.build` for setting `PLUGIN_SUFFIX` to the correct value for this platform.

CYGWIN: meson: support correct file extension for plugins.

---

.github/actions/install-dependencies/install-dependencies.sh
.github/workflows/c-cpp.yml

The macOS runner uses Python 3.12 meanwhile which removed
the distutils package, still required by gdbus-codegen.
See also: https://docs.python.org/3/whatsnew/3.12.html

CI: Fix macOS build by installing python setuptools

---

.github/actions/install-dependencies/action.yml
.github/workflows/c-cpp.yml

See also: https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages

CI: Use 64-bit for Windows and disable autotools build

---

.github/actions/install-dependencies/action.yml
.github/actions/install-dependencies/install-dependencies.sh
.github/actions/run-action/run-action.sh
meson.build
meson_options.txt

Qt 5 is no longer supported upstream and KDE has migrated as well.
Note that our Autotools build does not support Qt 6.
See also: https://doc.qt.io/qt-6/supported-platforms.html#supported-qt-versions

meson: Change default Qt version to 6

---

src/libaudgui/init.cc
src/libaudqt/audqt.cc

More and more distributions use Wayland by default now. Which brings new issues for Audacious, especially with the Winamp interface. Use X11/XWayland by default for now to avoid them.
See also:
- https://github.com/orgs/audacious-media-player/discussions/105
- https://github.com/orgs/audacious-media-player/discussions/1392
- https://github.com/orgs/audacious-media-player/discussions/1394
@madpilot78: Can you please verify that the `x11` GDK backend and `xcb` Qt platform can be used on FreeBSD? I'm not sure yet if we should apply this for Linux only.
@jlindgren90: Is this implemented properly? I have tested it successfully with a Ubuntu 24.04 VM.

Use X11/XWayland by default

---

.github/actions/install-dependencies/action.yml
.github/actions/install-dependencies/install-dependencies.sh
acinclude.m4
meson.build
src/libaudcore/tests/Makefile
src/libaudgui/infopopup.cc
src/libaudgui/libaudgui-gtk.h
src/libaudgui/libaudgui.h

See the commit messages for more details.
Is the infopopup approach acceptable for you, John? And could you please test it on Windows?
On X11 is has no effect while fixing the wrong popup position on Wayland.
P.S. My plan is to release Audacious 4.4 in the next days, probably this weekend, after updating all translations. Any objections?

Last fixes for Audacious 4.4

---

contrib/audacious.appdata.xml

Now mandatory for Flathub build, see:
https://docs.flathub.org/docs/for-app-authors/linter/#appstream-missing-developer-name

appdata: Add developer name

---

src/libaudcore/Makefile
src/libaudgui/Makefile
src/libaudqt/Makefile
src/libaudtag/Makefile

Buildsys no longer hardcodes it to 0 and doesn't use a fallback value.
See also: https://fl.nil.im/buildsys/vinfo/56ccacdc62ad446c

Set LIB_PATCH in makefiles for correct SONAMEs. Closes: #1408

---

src/libaudgui/list.cc

Calling both gtk_drag_get_data() and gtk_drag_finish() leads to drag and drop not working on Wayland and this error: "error reading selection buffer: Operation was cancelled"
See also: https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/927

audgui: Make drag and drop work on Wayland. Closes: #1423

---

.github/actions/install-dependencies/action.yml
win32/notes.html

UCRT64 is meanwhile the recommended MSYS2 environment for Windows.
Visual Studio uses it by default since 2015. tmpfile() behaves here
also as expected and does not always return NULL.
See also:
- https://www.msys2.org/docs/environments/
- https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt6
- https://github.com/msys2/MINGW-packages/issues/18878

CI: Switch from MINGW64 to UCRT64. Closes: #1421

---

.gitignore
mkrelease.sh

This allows users and packagers to verify them using
`sha256sum --check audacious-$version.sha256sum`

mkrelease: Calculate checksum for tarballs. Closes: #1432

---

src/libaudqt/font-entry.cc

"PxPlus ToshibaSat 9x16 Bold 8" from the Oldschool PC Font Pack is such an example.
To parse the font family correctly, we need to check if all characters for the font size are digits.
Both `str_to_int()` and `atoi()` do not support this.
Use `strtol()` instead and check `endptr` accordingly.
Closes: #1483

audqt: Parse font family names containing digits correctly

---

src/libaudqt/audqt.cc

See audacious-media-player/audacious-plugins#174
Sorry, forgot about skins since I don't typically use them. Since the signal handler is sufficiently decoupled via `aud_ui_show` anyway, I was thinking it would be cleaner to just hook this directly where the QApplication is instantiated along with the other platform specific code.

Make UI appear on Qt::ApplicationActive for macOS

---

src/libaudqt/audqt.cc
src/libaudqt/song-window-qt.cc

Opening the dialog and searching entries leaked memory every time.

audqt: Plug massive memory leaks in Jump-to-Song dialog

---

src/libaudgui/playlists.cc
src/libaudqt/fileopener.cc

This is more user-friendly since the playlist entries of the current playlist are not overwritten without confirmation.

audgui/audqt: Create new playlist when importing one. Closes: #1508

---

src/libaudgui/Makefile
src/libaudgui/init.cc
src/libaudgui/internal.h
src/libaudgui/meson.build
src/libaudgui/settings-portal.cc

Audacious then follows the preferred color scheme and even updates its appearance on the fly when the setting changes.
See also:
- https://blogs.gnome.org/alicem/2021/10/04/dark-style-preference/
- https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference#other
- https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html
- https://wiki.archlinux.org/title/Dark_mode_switching

audgui: Read color scheme from settings portal. Closes: #1469

---

contrib/audacious.appdata.xml
src/libaudtag/id3/id3-common.cc

Blues is represented as "(0)" if the tag is saved numerically.
With atoi() we can't distinguish if we got a valid numeric genre
because it returns also 0 when parsing strings like "Blues".
Use sscanf() instead which is more reliable here.
See also: https://en.wikipedia.org/wiki/List_of_ID3v1_genres

audtag: Parse ID3 genre tag Blues correctly. Closes: #1643
